DECLARE @Fecha DATETIME = GETDATE()

INSERT Area (Nombre,Activo, UsuarioCrea,FechaCrea) VALUES
('MANTENIMIENTO',1,'MIGRACION',@Fecha),
('OPERACIONES',1,'MIGRACION',@Fecha),
('RECURSOS HUMANOS',1,'MIGRACION',@Fecha),
('LEGAL',1,'MIGRACION',@Fecha),
('FINANZAS',1,'MIGRACION',@Fecha),
('TRANSFORMACIÓN',1,'MIGRACION',@Fecha),
('HSSE',1,'MIGRACION',@Fecha),
('IMPLEMENTACIÓN Y PROYECTO',1,'MIGRACION',@Fecha),
('SISTEMAS',1,'MIGRACION',@Fecha),
('COMERCIAL',1,'MIGRACION',@Fecha),
('GERENCIA',1,'MIGRACION',@Fecha),
('LEGAL Y RELACIONES LABORALES',1,'MIGRACION',@Fecha),
('IMPLEMENTACIÓN_Y_PROYECTO',1,'MIGRACION',@Fecha),
('TRANSFORMACION',1,'MIGRACION',@Fecha)